# Generated by Django 3.2 on 2022-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site1',
            name='pro_discription',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='site1',
            name='pro_size',
            field=models.CharField(max_length=20),
        ),
    ]
