# Generated by Django 3.2 on 2022-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220924_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site1',
            name='pro_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
